#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   - Database Settings -
# This plugin requires an MySQL database to store information about the
# users. Fill out the information below to make the plugin functional.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
mysql:
  host: ''
  port: ''
  database: ''
  username: ''
  password: ''

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   - Custom Server List Options -
# You can use '&' for color codes.
# Use - to indicate a new line with another option.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
server-motd:
  - '&cSexy Minecraft Server Here'
server-motd-hover:
  - 'Website - https://voxmc.com'
  - 'Reddit  - https://reddit/com/r/voxmc'
  - 'Discord - https://discord.gg/BCBMZTs'
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   - Player join messages -
# You can use '&' for color codes.
# Use - to indicate a new line with another motd option.
# Use %player% to stub in the joining player's display name.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
player-motd:
  - '&eWelcome back %player%!'
  - '&eHey %player%! Enjoy your stay!'
  - '&eDon''t forget to read the &6/rules&e!'
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   - Joining the server for the first time -
# The announcement is a list of options, one will be used at random.
# You can use '&' for color codes.
# This is also where you set up the first join spawn and create optional
# messages for the /welcome command
# Use %player% to stub in the joining player's display name.
# In spawn locations yaw is the horizontal view direction, and pitch
# is the vertical view direction.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
first-join-announcements:
  - Welcome %player% to the server!
  - Never gonna give %player% up, never gonna let %player% down
  - Say hello to %player%!
first-join-message:
  - Hello %player%! Welcome to the Server!
  - Hey %player%! Please read the /rules and have a great time!
welcome-messages:
  - Welcome to the server %player%!
  - Nice to see you %player%! Have a great time!
first-join-spawn:
  world: 'world'
  x: 0.5
  y: 65.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   - Server Spawn Locations -
# In spawn locations yaw is the horizontal view direction, and pitch
# is the vertical view direction. All spawns can be overridden with the
# /setspawn <world|death> command, using the location of the command
# executor.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
world-spawn: # /spawn
  world: 'world'
  x: 0.5
  y: 65.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0
death-spawn:
  world: 'world'
  x: 0.5
  y: 65.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0
nether-spawn:
  world: 'nether'
  x: 0.5
  y: 65.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   - Player Homes -
# You can assign homes by creating new keys under player-homes, each
# will be checked against a player's corresponding homes permission.
# You will need to manage your permissions with another plugin,
# LuckPerms is a good option. Make sure to name your permissions
# lemonaid.homes.<groupname> where <groupname> corresponds with the keys
# listed under player-homes. You can also use lemonaid.homes.unlimited
# as needed, operators automatically inherit this node.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
player-homes:
  default: 3
  vip: 5 # lemonaid.homes.vip
  staff: 10 # lemonaid.homes.staff

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   - Moderation settings -
# Setting you can manipulate for groups inheriting lemonaid.ignoreexempt
# You can allow your moderators to add players to their ignore list by
# setting allow-moderator-ignore to true.
# Moderators can set themselves to busy but will still receive a copy
# of the direct message when a player tries to contact them (the player
# will get a warning of the mod being busy), unless set to true.
# Players with the lemonaid.duty permission can toggle their duty status
# by using /duty. Add permissions to be granted (temporarily) to the
# duty-permissions.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
allow-moderator-ignore: false # Allow moderators to add players to their ignore list
allow-moderator-busy: false # Allow moderators to ignore msg etc while busy
duty-inventory: true # Give a player a temporary clean inventory while in duty
duty-creative: true # Set a player's game mode to creative while in duty
duty-permissions:
  - lemonaid.reload
  - lemonaid.kits.admin
  - lemonaid.homes.unlimited







#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   - Teleportation -
# All timers are in seconds. All teleport options need their below
# settings, but you can tweak the numbers as necessary.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
teleport:
  # Cancel a teleportation countdown by walking or jumping
  cancel-countdown: true
  # Player to Player teleport event
  tpa:
    timer: 3
    cost: 100
    cross-world: false
    request-timer: 30 # time before a request expires
  tpahere:
    timer: 3
    cost: 100
    cross-world: false
    request-timer: 30
  ptp:
    timer: 15
    cost: 500
    cross-world: true
    request-timer: 30
  ptphere:
    timer: 15
    cost: 500
    cross-world: true
    request-timer: 30
  # Player to Location teleport event
  back:
    timer: 5
    cost: 0
    cross-world: true
  home:
    timer: 3
    cost: 0
    cross-world: true
  spawn: # Teleport to world spawn defined above
    timer: 5
    cost: 0
    cross-world: true
  warp:
    timer: 1
    cost: 10
    cross-world: true
  random:
    timer: 5
    cost: 10
    cross-world: true
    world: 'world'
    radius: 1000 # size of the block radius around 0,0 on your designated world
    safety-check: true # players will not spawn in lava etc
    water-spawn: true # water blocks are considered a safe location


#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   - Social Settings -
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
local-chat-radius: 80

