#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   Plugin information
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
name: Lemonaid
version: ${project.version}
main: me.saurpuss.lemonaid.Lemonaid
authors: [SaurPuss]
description: Lots of basic commands put together in one plugin
database: true
website: https://voxmc.com
softdepend: [Vault, WorldGuard]
permission-message: &noperms "§cYou don't have permission to do this!"

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   Commands
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
commands:
  # Plugin specific commands
  lemonaid:
    description: Lemonaid specific commands
    usage: |
      /<command> info - Plugin information
      /<command> reload - Reload the plugin configs
      /<command> ?|help - Plugin help file
    aliases: [lemon]

  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
  #   Administrator commands
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
  broadcast:
    description: Broadcast a message across the server
    usage: /<command> [message...]
    aliases: [bc]
    permission: lemonaid.broadcast
    permission-message: *noperms
  fly:
    description: Toggle fly mode
    usage: |
      /<command> - Toggle fly on yourself
      /<command> [target] - Toggle fly on a valid target
    permission: lemonaid.fly
    permission-message: *noperms
  globalmute:
    description: |
      Prevent every player without the globalmute or exempt permission from using
      chat. Does not persist through restart.
    usage: /<command>
    aliases: [silence]
    permission: lemonaid.globalmute
    permission-message: *noperms
  mastercuff:
    description: |
      Lock every player without the mastercuff or exempt permission in place and
      prevent them from using chat. Does not persist through restart.
    usage: |
      /<command> - Toggle mastercuff for all online players
      /<command> on|off - Toggle mastercuff on or off for all online players
    permission: lemonaid.mastercuff
    permission-message: *noperms

  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
  #   Moderation commands
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
  mute:
    description: Prevent a player from speaking
    usage: |
      /<command> list - Display last 10 mute logs
      /<command> help|? [#] - Display mute help (page number optional)
      /<command> [target] - Mute player indefinitely, apply again to unmute
      /<command> [target] [time] - Mute a player for a specific amount of time
       (0 = forever | number + time: s = seconds, m = minutes, h = hours, d = days,
       w = weeks, y = years, "10m = 10minutes")
      /<command> [target] [time] [reason] - Mute a player for a specific amount of
       time and log the reason
      /<command> [target] 0 [reason] - Mute a player indefinitely for a specific
       reason
    permission: lemonaid.mute
    permission-message: *noperms
  cuff:
    description: Lock an offending player in place and prevent them from using chat
    usage: |
      /<command> list - Display last 10 cuff logs
      /<command> help|? [#] - Display cuff help (page number optional)
      /<command> [target] - Toggle cuff on|off for your target
      /<command> [target] [reason...] - Toggle cuff on a player and log a reason
    permission: lemonaid.cuff
    permission-message: *noperms
  recap:
    description: Log quick recaps for information hand-off
    usage: |
      /<command> - Display last 10 recaps
      /<command> [message...] - Add recap
    permission: lemonaid.recap
    permission-message: *noperms

  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
  #   Social commands
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
  msg:
    description: Whisper to another player
    usage: /<command> [target] [message...]
    aliases: [tell, whisper]
    permission: lemonaid.chat.private
    permission-message: *noperms
  reply:
    description: Reply to a whispered message
    usage: /<command> [message...]
    aliases: [r]
    permission: lemonaid.chat.private
    permission-message: *noperms
  busy:
    description: Prevent incoming whispers and tp requests
    usage: /<command>
    aliases: [dnd]
    permission: lemonaid.chat.busy
    permission-message: *noperms
  ignore:
    description: Ignore all messages and tp requests from another player
    usage: |
      /<command> - Display your ignored list
      /<command> [target] - Add or remove your target from your ignore list
    permission: lemonaid.chat.ignore
    permission-message: *noperms

  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
  #   Teleportation commands
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
  tpa:
    description: Send a teleportation request to another player
    usage: /<command> [target]
    permission: lemonaid.teleport.tpa
    permission-message: *noperms
  tpahere:
    description: Request another player teleport to your location
    usage: /<command> [target]
    permission: lemonaid.teleport.tpahere
    permission-message: *noperms
  tpaccept:
    description: Accept a teleportation request from another player
    usage: /<command>
    permission: lemonaid.teleport.tpacccept
    permission-message: *noperms
  tpdeny:
    description: Deny or cancel a pending teleportation request
    usage: /<command>
    aliases: [tpacancel, tpcancel]
    permission: lemonaid.teleport.tpaccept
    permission-message: *noperms
  back:
    description: Return to your last saved location
    usage: /<command>
    permission: lemonaid.teleport.back
    permission-message: *noperms















  home:
    description: Allow players to set and teleport to personal homes
    usage: |
      /<command> - Go to your singular home, or display all homes
      /<command> set [name] - Set a new home, if [name] is not used
       it will default to home.
      /<command> delete|remove <name> - Remove a homeset
      /<command> list - Display all your homesets
    permission: lemonaid.teleport.home
    permission-message: *noperms

  localchat:
    description: Talk to the players within earshot
    usage: |
      /<command> - Toggle chat channel
      /<command> message - Send a message in the local chat channel
    aliases: [l, lc, local]
    permission: lemonaid.chat.local
    permission-message: *noperms

  # Party commands
  party:
    description: All party all the time
    usage: |
      /<command> - Display party help, or toggle to party chat
      /<command> new [party_name] - Create a party, be careful to avoid spaces
      /<command> invite [target] - Invite a player to your party
      /<command> accept - Accept an invitation to a party
      /<command> join [party_name] - Join an (open invite) party
      /<command> set - Display your party settings
      /<command> set [setting] [on|off] - Toggle a party setting
      /<command> set [open|invite|closed] - Open parties can be joined by anyone,
      invite parties can be joined by invite from members, closed parties can only
      be joined when the leader or an assistant invites.
      /<command> assistant [target] - Toggle party assistant status, when true you
      are giving this player permission to modify your party settings
    #      /<command> accept [player_name] - Accept an request to join your party
    permission: lemonaid.party.*
    permission-message: *noperms

  slowchat:
    description: Toggle slow chat for all players
    usage: /<command>
    default: OP
    aliases: [slow]
    permission: lemonaid.slow
    permission-message: *noperms
  clearchat:
    description: Push that pesky chat out of scroll range
    usage: /<command>
    default: OP
    aliases: [cc]
    permission: lemonaid.clearchat
    permission-message: *noperms



#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#   Permissions
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
permissions:
  lemonaid.admin:
    description: Admin level permissions for Lemonaid
    default: op
    children:
      lemonaid.fly: true
      lemonaid.broadcast: true
      lemonaid.mute: true
      lemonaid.exempt: true
      lemonaid.globalmute: true
      lemonaid.recap: true
      lemonaid.setignore: true
      lemonaid.cuff: true
      lemonaid.mastercuff: true
      lemonaid.jail: true
      lemonaid.slow: true
      lemonaid.clearchat: true
  lemonaid.moderation:
    description: Moderation permissions for non-admins
    default: false
    children:
      lemonaid.exempt: true
      lemonaid.mute: true
      lemonaid.cuff: true
      lemonaid.clearchat: true
      lemonaid.chat.color: true
  lemonaid.exempt:
    description: |
      Moderation permission to be notified of moderation events and
      creates exemption from global moderation effects
    default: false
    children:
      lemonaid.notify: true
  lemonaid.reload:
    description: Reload plugin configuration files
    default: false
  lemonaid.basic:
    description: Basic perm nodes that are on by default
    default: true
    children:
      lemonaid.chat.private: true
      lemonaid.chat.busy: true
      lemonaid.chat.ignore: true
      lemonaid.teleport: true
      lemonaid.home: true
  lemonaid.teleport:
    description: Basic perm nodes for teleportation
    default: true
    children:
      lemonaid.teleport.tpa: true
      lemonaid.teleport.tpahere: true
      lemonaid.teleport.tpaccept: true
      lemonaid.teleport.back: true
      lemonaid.teleport.home: true
  lemonaid.chat.color:
    description: Allow the use of colors with & color codes
    default: op

