name: Lemonaid
version: ${project.version}
main: me.saurpuss.lemonaid.Lemonaid
authors: [SaurPuss]
description: Lots of basic commands put together in one plugin
website: https://voxmc.com
softdepend: [Vault, WorldGuard]

commands:
  # Plugin specific commands
  lemonaid:
    description: Lemonaid specific commands
    usage: |
      /<command> info - Plugin information
      /<command> reload - Reload the plugin configs
      /<command> ?|help - Plugin help file
    default: OP
    permission: lemonaid.admin.reload
    permission-message: You do not have permission to do this

  # Chat commands
  msg:
    description: Whisper to another player
    usage: /<command> [target] message
    aliases: [tell, whisper]
    permission: lemonaid.chat.private
    permission-message: You do not have permission to do this
  reply:
    description: Reply to a whispered message
    usage: /<command> message
    aliases: [r]
    permission: lemonaid.chat.private
    permission-message: You do not have permission to do this
  busy:
    description: Prevent incoming whispers and tp requests
    usage: /<command>
    aliases: [dnd]
    permission: lemonaid.chat.busy
    permission-message: You do not have permission to do this
  ignore:
    description: Ignore all messages and tp requests from another player
    usage: |
      /<command> - Display your ignored list
      /<command> [target] - Add or remove your target from your ignore list
    permission: lemonaid.chat.ignore
    permission-message: You do not have permission to do this
  localchat:
    description: Talk to the players within earshot
    usage: |
      /<command> - Toggle chat channel
      /<command> message - Send a message in the local chat channel
    aliases: [l, lc, local]
    permission: lemonaid.chat.local
    permission-message: You do not have permission to do this

  # Party commands
  party:
    description: All party all the time
    usage: |
      /<command> - Display party help, or toggle to party chat
      /<command> new [party_name] - Create a party, be careful to avoid spaces
      /<command> invite [target] - Invite a player to your party
      /<command> accept - Accept an invitation to a party
      /<command> join [party_name] - Join an (open invite) party
      /<command> set - Display your party settings
      /<command> set [setting] [on|off] - Toggle a party setting
      /<command> set [open|invite|closed] - Open parties can be joined by anyone,
      invite parties can be joined by invite from members, closed parties can only
      be joined when the leader or an assistant invites.
      /<command> assistant [target] - Toggle party assistant status, when true you
      are giving this player permission to modify your party settings
    #      /<command> accept [player_name] - Accept an request to join your party
    permission: lemonaid.party.*
    permission-message: You do not have permission to do this

#  partychat:
#    description: Talk to online members of your party
#    usage: /<command> message
#    default: true
#    aliases: [pc]
#    permission: lemonaid.chat.party
#    permission-message: You do not have permission to do this

  # Teleportation commands
  tpa:
    description: Send a teleportation request to another player
    usage: /<command> [target]
    default: true
    permission: lemonaid.teleport.tpa
    permission-message: You do not have permission to do this
  tpahere:
    description: Request another player teleport to your location
    usage: /<command> [target]
    permission: lemonaid.teleport.tpahere
    permission-message: You do not have permission to do this
  tpaccept:
    description: Accept a teleportation request from another player
    usage: /<command>
    permission: lemonaid.teleport.tpaccept
    permission-message: You do not have permission to do this
  tpdeny:
    description: Deny or cancel a pending teleportation request
    usage: /<command>
    aliases: [tpacancel, tpcancel]
    permission: lemonaid.teleport.tpadeny
    permission-message: You do not have permission to do this
  back:
    description: Return to your last saved location
    usage: /<command>
    permission: lemonaid.teleport.back
    permission-message: You do not have permission to do this

  # OP level commands
  fly:
    description: Toggle fly mode
    usage: /<command>
    default: OP
    permission: lemonaid.admin.fly
    permission-message: You do not have permission to do this
  broadcast:
    description: Broadcast a message across the server
    usage: /<command> message
    default: OP
    aliases: [bc]
    permission: lemonaid.admin.broadcast
  cuff:
    description: Lock an offending player in place and prevent them from using chat.
    usage: |
      /<command> log - Show a log of cuffs
      /<command> list - Show a list of currently cuffed online players
      /<command> list all - Show a list of currently cuffed online and offline players
      /<command> [target] - Toggle cuff on and off for your target
      /<command> [target] offline - Cuff an offline player
      /<command> [target] [time] - Cuff a player for an amount of time
      /<command> [target] [time] [reason] - Cuff a player for an amount of time and log the reason
    default: OP
    permission: lemonaid.admin.cuff
  jail:
    description: Send a player to a jail defined by a World Guard region
    usage: /<command> [target]
    default: OP
    permission: lemonaid.admin.jail
  mute:
    description: Prevent a player from speaking
    usage: |
      /<command> - Display last 10 mute logs
      /<command> [target] - Mute player indefinitely, apply again to unmute
      /<command> [target] [time] - Mute a player for a specific amount of time
      (0 = indefinite | number + time: s = seconds, m = minutes, h = hours, d = days, y = years, "10m = 10minutes")
      /<command> [target] [time] [reason] - Mute a player for a specific amount of time and log the reason
      /<command> [target] [reason] - Mute a player indefinitely for a specific reason
    default: OP
    permission: lemonaid.admin.mute
  slowchat:
    description: Toggle slow chat for all players
    usage: /<command>
    default: OP
    aliases: [slow]
    permission: lemonaid.admin.slow
  clearchat:
    description: Push that pesky chat out of scroll range
    usage: /<command>
    default: OP
    aliases: [cc]
    permission: lemonaid.admin.clearchat
  recap:
    description: Log quick recaps for information hand-off
    usage: |
      /<command> - Display last 10 recaps
      /<command> [message] - Add recap
    default: OP
    permission: lemonaid.admin.recap




permissions:
  lemonaid.admin.*:
    description: Admin level permissions for Lemonaid
    default: op
    children:
      lemonaid.admin.fly: true
      lemonaid.admin.broadcast: true
      lemonaid.admin.reload: true
      lemonaid.admin.notify: true
      lemonaid.admin.cuff: true
      lemonaid.admin.mute: true
      lemonaid.admin.recap: true
      lemonaid.admin.jail: true
      lemonaid.admin.slow: true
      lemonaid.admin.clearchat: true
  lemonaid.admin.notify.*:
    description: Notifications for moderators on specific event
    default: op
    children:
      lemonaid.admin.notify.login: true
      lemonaid.admin.notify.logout: true
      lemonaid.admin.notify.kick: true
      lemonaid.admin.notify.mute: true
      lemonaid.admin.notify.cuff: true
      lemonaid.admin.notify.jail: true
      lemonaid.admin.slow.exempt: true
      lemonaid.admin.clearchat.exempt: true
  lemonaid.chat.*:
    description: |
      Permissions for different chats. Toggle if you prefer to
      set them differently for groups or players.
    default: true
    children:
      lemonaid.chat.local: true
      lemonaid.chat.private: true
      lemonaid.chat.colors: true
      lemonaid.chat.busy: true
      lemonaid.chat.ignore: true
#      lemonaid.chat.party: true
  lemonaid.teleport.*:
    description: Permissions for teleportation
    default: true
    children:
      lemonaid.teleport.tpa: true
      lemonaid.teleport.tpahere: true
      lemonaid.teleport.tpaccept: true
      lemonaid.teleport.tpdeny: true
  lemonaid.party.*:
    description: Permission to form, join, and edit parties
    default: true
    children:
      lemonaid.party.create: true
      lemonaid.party.join: true
      lemonaid.party.leave: true
      lemonaid.party.leader: false
      lemonaid.party.temporary: false
      lemonaid.party.assistant: false
  lemonaid.party.leader.*:
    description: |
      Permission added to a party creator setting their edit
      and remove permissions to true.
    default: false
    children:
      lemonaid.party.leader.remove: true
      lemonaid.party.leader.edit: true
      lemonaid.party.leader.share: true
  lemonaid.party.assistant:
    description: Give permission to edit the party as an assistant.
    default: false
  lemonaid.party.temporary:
    description: Create temporary parties.
    default: false
